image: Visual Studio 2015

init:
- git config --global core.autocrlf input

#clone_folder: c:\projects\native-web-app
#shallow_clone: true

matrix:
  fast_finish: false

platform:
- x64
- x86

configuration:
- Debug
- Release

environment:
  matrix:
  - TOOLCHAIN: msvc10
  - TOOLCHAIN: msvc12
  - TOOLCHAIN: msvc14

install:
#- call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%
- appveyor DownloadFile https://github.com/google/googletest/archive/release-1.8.1.zip -FileName googletest.tar.gz
#- 7z e -y googletest.tar.gz -o"googletest"
- 7z x -y "googletest.tar.gz" -o"C:\" > nul
- cd C:\googletest-release-1.8.1\
#- cd googletest/googletest.tar/googletest-release-1.8.1/
#- dir /s /b /o:gn
- cmake -Bbuild -H.
#- mkdir build
- cd build
- dir /s /b /o:gn
#- cmake ..
#- make
#- make install

build_script:
- mkdir build
- cd build
- cmake .. %CMAKE_CONFIGURE_FLAGS%
- cmake --build %CMAKE_BUILD_FLAGS% -DBUILD_TESTS=OFF .

test_script:
- C:\googletest-release-1.8.1\build\ctest.exe -C %CONFIGURATION% --output-on-failure
