image: Visual Studio 2015

init:
- git config --global core.autocrlf input

matrix:
  fast_finish: false

platform:
- x64
- x86

configuration:
- Debug
- Release

environment:
  matrix:
  - TOOLCHAIN: msvc10
  - TOOLCHAIN: msvc12
  - TOOLCHAIN: msvc14

build_script:
- cd %APPVEYOR_BUILD_FOLDER%
- mkdir build
- cd build
#- cmake .. -DCI_TESTS=OFF %CMAKE_CONFIGURE_FLAGS%
- cmake .. %CMAKE_CONFIGURE_FLAGS%
- cmake --build . --target install

#test_script:
#- C:\projects\gfb-stdgo\build\test\gfb-stdgo-test.exe
#- ctest -C %CONFIGURATION% --output-on-failure
